all:
	gcc sample1.c -o sample1 -lglut -lGL -lm
	gcc sample3.c -o sample3 -lglut -lGL

sample1: sample1.c
	gcc sample1.c -o sample1 -lglut -lGL -lm
sample3: sample3.c
	gcc sample3.c -o sample3 -lglut -lGL
